### ISSUE TITLE
Files stopped syncing (CampusNetSync)

### ISSUE THREAD

**Issue by askf0123** [tmpethick/campusnet-electron#6]
Hi, great application! very fond of it. But resent 3 days the application hasn't been syncing my files. I tried relocating file-directory, login in and out, reinstalling, but nothing seems to work. I would greatly appreciate if you could help me out.

Regards
Ask

**Comment by tmpethick** [comment]
Thanks for letting me know - it hasn't been an issue on mac which I'm running. I'll spin up a windows instance in the weekend and debug it..

**Comment by askf0123** [comment]
Quick response! Thank you!

2018-02-08 15:11 GMT+01:00 Thomas Pethick <notifications@github.com>:

**Comment by Kambonde** [comment]
I have the same problem on my macbook. Fingers crossed, you can help us.

**Comment by tmpethick** [comment]
Okay, that took some time, but the app is now fixed for both Windows and Mac. However(!), note:

I have updated the electron version and with it the auto updater – and unfortunately it is not backwards compatible. So you will have to download the newest version for Windows from http://pethick.dk/campusnet-electron/.

Concerning Mac the previous auto updater actually works but throws an error. You can ignore that, since it will still install the newest version correctly.

I've:

* Added version number in the dropdown menu (should be v1.0.10).
* Changed the header name to "DTU Inside" to make the DTU marketing department happy. However, I have _not_ changed the app name since you would loose your configuration and thus have to login again.
* Moved to NSIS instead of Squirrel on Windows. It should provide cleaner installation and updating.

Enjoy! (and keep complaining if anything is still not working..!)

**Comment by askf0123** [comment]
Great man! works again

2018-02-15 14:36 GMT+01:00 Thomas Pethick <notifications@github.com>:
